basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: |-
    拼车车App后台服务器,主要提供容器集群调度服务.
    <a href='?docExpansion=none'>折叠</a>  <a href='index.html'>展开</a>
  license: {}
  title: 拼车车App后台服务器API文档
  version: "0.2"
paths: {}
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
