server:
  runmode: debug    # {debug | release | test}
  addr: :9001
  name: apiserver
  url: http://127.0.0.1:9001
  max_ping_count: 10
  jwt_secret: da39a3ee5e6b4b0d3255bfef95601890afd80709
#  tls:
#    addr: :8081
#    cert: conf/myth.pem
#    key: conf/myth.key
db:
  runmode: dev  # {dev | pro}
  gormlog: true   # 数据库日志
  db_max_idle: 10
  db_max_conn: 100
  dev:
    name: chenler_pcc_1_0
    addr: 47.92.202.208:3306
    username: root
    password: clmAdm1n
  pro:
    name: chenler_pcc_1_0
    addr: 47.92.202.208:3306
    username: root
    password: clmAdm1n
alibaba:
  ak: LTAI4G9oWtNy13v3DCw9jQSD
  sk: sGKRUwn3R7XhLy91l5ZptE6eYTBaz0
log:
  writers: file,stdout
  logger_level: DEBUG   # {DEBUG | INFO | WARN | ERROR | FATAL}
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7